// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagement.WebAPI.Models;

public partial class ClassSubject
{
    public int ClassSubjectId { get; set; }

    public int ClassId { get; set; }

    public int SubjectId { get; set; }

    public int TeacherId { get; set; }

    public virtual Class Class { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual User Teacher { get; set; }
}