// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SchoolManagement.Models.Models;

public partial class ClassSubject
{
  public int ClassSubjectId { get; set; }

  public int ClassId { get; set; }

  public int SubjectId { get; set; }

  public int TeacherId { get; set; }
  [JsonIgnore]
  public virtual Class Class { get; set; }
  [JsonIgnore]
  public virtual Subject Subject { get; set; }
  [JsonIgnore]
  public virtual User Teacher { get; set; }
}
