// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagement.Models.Models
{
    public partial class Class
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public int? TeacherId { get; set; }
        public string Schedule { get; set; }
        public string Room { get; set; }
        public int? StudentCount { get; set; }
    }
}