// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagement.Models.Models
{
    public partial class Student
    {
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public int ClassId { get; set; }
        public DateTime? EnrollmentDate { get; set; }
    }
}