// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolManagement.Models.Models
{
    public partial class Student
    {
        [Key]
        [Column("StudentID")]
        public int StudentId { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        [Column("ClassID")]
        public int ClassId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EnrollmentDate { get; set; }
    }
}