// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SchoolManagement.Models.Models
{
    public partial class Student
    {
        public Student()
        {
            Grades = new HashSet<Grade>();
        }

        public int StudentId { get; set; }
        public int UserId { get; set; }
        public int ClassId { get; set; }
        public DateTime? EnrollmentDate { get; set; }

        public virtual Class Class { get; set; }
        public virtual User User { get; set; }
    [JsonIgnore]
    public virtual ICollection<Grade> Grades { get; set; }
    }
}
