// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace SchoolManagement.Models.Models;

public partial class Subject
{
  public int SubjectId { get; set; }

  public string SubjectName { get; set; }

  public string Description { get; set; }
  [NotMapped]
  [JsonIgnore]
  public virtual ICollection<ClassSubject> ClassSubjects { get; set; } = new List<ClassSubject>();
  [NotMapped]
  [JsonIgnore]
  public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();
  [NotMapped]
  [JsonIgnore]
  public virtual ICollection<Timetable> Timetables { get; set; } = new List<Timetable>();
}
