// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SchoolManagement.Models.Models
{
    public partial class Subject
    {
        [Key]
        [Column("SubjectID")]
        public int SubjectId { get; set; }
        [Required]
        [StringLength(50)]
        public string SubjectName { get; set; }
        [StringLength(255)]
        public string Description { get; set; }
    }
}