// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace SchoolManagement.Models.Models
{
    public partial class Timetable
    {
        [Key]
        [Column("TimetableID")]
        public int TimetableId { get; set; }
        [Column("ClassID")]
        public int ClassId { get; set; }
        [Column("SubjectID")]
        public int SubjectId { get; set; }
        [StringLength(10)]
        public string DayOfWeek { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        [StringLength(50)]
        public string Room { get; set; }
    }
}